"""empty message

Revision ID: 03bd24db1249
Revises: 
Create Date: 2019-08-27 00:35:39.153285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bd24db1249'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('poiId', sa.Integer(), nullable=False),
    sa.Column('poiName', sa.String(length=120), nullable=True),
    sa.Column('poiLat', sa.Float(), nullable=True),
    sa.Column('poiLng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('poiId')
    )
    op.create_index(op.f('ix_pois_poiName'), 'pois', ['poiName'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_pois_poiName'), table_name='pois')
    op.drop_table('pois')
    # ### end Alembic commands ###
